name: Deploy Quartz site to GitHub Pages

on:
  push:
<<<<<<< HEAD
    branches: ["main"]
=======
<<<<<<< HEAD
    branches:
      - v5
=======
    branches: ["main"]
>>>>>>> e871efbfe6cae8860f3015be06febf642bd2a9f4
>>>>>>> 58144f0cfbb5ef5f81f4e50f5d680dcff23dd28f

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm ci
<<<<<<< HEAD
      - name: Install Plugins
        run: npx quartz plugin install
=======
<<<<<<< HEAD
=======
      - name: Install Plugins
        run: npx quartz plugin install
>>>>>>> e871efbfe6cae8860f3015be06febf642bd2a9f4
>>>>>>> 58144f0cfbb5ef5f81f4e50f5d680dcff23dd28f
      - name: Build Quartz
        run: npx quartz build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
<<<<<<< HEAD
        uses: actions/deploy-pages@v4
=======
<<<<<<< HEAD
        uses: actions/deploy-pages@v4
=======
        uses: actions/deploy-pages@v4
>>>>>>> e871efbfe6cae8860f3015be06febf642bd2a9f4
>>>>>>> 58144f0cfbb5ef5f81f4e50f5d680dcff23dd28f
